# Generated by Django 3.2.8 on 2021-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('board', models.CharField(max_length=120)),
                ('fee', models.IntegerField(default=False)),
            ],
        ),
    ]
